version: '3.7'

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: zarla
      POSTGRES_PASSWORD: zarla1234
      POSTGRES_DB: e-commerce-db
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zarla.com
      PGADMIN_DEFAULT_PASSWORD: zarla1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # TODO: Cannot Access to NIFI from the localhost
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
      - "9443:9443"
    environment:
      NIFI_WEB_HTTP_PORT: '9443'
      NIFI_WEB_HTTPS_PORT: '8443'
      SINGLE_USER_CREDENTIALS_USERNAME: zarla-admin
      SINGLE_USER_CREDENTIALS_PASSWORD: zarla12345678
    volumes:
      - ./data:/opt/nifi/data
      - ./jdbc_drivers:/opt/nifi/nifi-current/lib/ext # Mounting JDBC drivers

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: e-commerce-db
      CLICKHOUSE_USER: zarla 
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 
      CLICKHOUSE_PASSWORD: zarla1234
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
      - "9000:9000"

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: hDTxDa1BC/3sEbnuRwHaLNQwVwFOGcKplbvS8xi4dmt6u636dkboDHHy
      TALISMAN_ENABLED: false
    volumes:
      - ${PWD}/superset_home:/app/superset_home

volumes:
  postgres_data:
  clickhouse_data:
  superset_home:
